name: Testing GSSAR
"on":
  workflow_dispatch:
jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: stelligent/cfn_nag@master
        with:
          extra_args: -o sarif
          output_path: cfn_nag.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: cfn_nag.sarif
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  LintCloudFormation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint -t ./template.yml

