name: Testing GSSAR
"on":
  workflow_dispatch:
jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@0.0.18
        with:
          suppress_push_for_open_pull_request: 1
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@prerelease
          post_comment: 0
          use_magic_file: 1
          experimental_apply_changes_via_bot: 1
          use_sarif: 1
          extra_dictionary_limit: 10
      - uses: stelligent/cfn_nag@master
        with:
          extra_args: -o sarif
          output_path: cfn_nag.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cfn_nag.sarif
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  LintCloudFormation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint -t ./template.yml
